trigger:
- master

name: Create Repo

parameters:
- name: RepoName
  displayName: Repo to be created

variables:
  group: secrets
  azureServiceConnection: 'ash2'
  orgUrl: 'https://dev.azure.com/Dappverse'
  projectName: 'Alz'


pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

stages:
- stage: Create_Repo
  jobs:
  - job: Create_Repo
    displayName: 'Create Azure Repo'
    steps:
    - checkout: none
    - script: |
        echo $(CLIENTID) 
        echo "Logging in to Azure..."
        az login --service-principal -u $(CLIENTID) -p $(CLIENTSECRET) --tenant $(TENANTID)
      
        # Rest of your steps...
      displayName: 'Setup Azure Repo'
