trigger:
- master

name: CreateRepo

parameters:
- name: RepoName
  displayName: Repo to be created

variables:
  group: secrets
  azureServiceConnection: 'ash3'
  orgUrl: 'https://dev.azure.com/Dappverse'
  projectName: 'Alz'

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

stages:
- stage: CreateRepo
  jobs:
  - job: CreateRepo
    displayName: 'Create Azure Repo'
    steps:
    - checkout: none
    - script: |
        # echo $(CLIENTID)
        # echo "Logging in to Azure..."
        # az login --service-principal -u $(CLIENTID) -p $(CLIENTSECRET) --tenant $(TENANTID)
      
        # Rest of your steps...
        echo "Configuring defaults..."
        az devops configure --defaults organization=$(orgUrl) project=$(projectName)
   
        echo "Creating a new Azure Repo named ${{parameters.RepoName}}..."
        az repos create --name ${{parameters.RepoName}}
   
        echo "Creating folders in the repository..."
        git clone $(Orgurl/parameters.RepoName) ${{parameters.RepoName}}
        cd ${{parameters.RepoName}}
        mkdir folder1 folder2 folder3
        git add .
        git commit -m "Create initial folders"
        git push origin main
   
        echo "Applying build policy to the repository..."
        az repos policy build create --blocking true --branch master --build-definition-id $(buildDefinitionId) --display-name "Build Policy" --enabled true --manual-queue-only false --queue-on-source-update-only true --repository-id $(repositoryId) --valid-duration 0
