trigger:
- master

name: Create Repo

parameters:
- name: RepoName
  displayName: Repo to be created

variables:
  azureServiceConnection: 'ash2'
  orgUrl: 'https://dev.azure.com/Dappverse'
  projectName: 'Alz'
  group: secrets
  ClientId: $(ClientId)
  ClientSecret: $(ClientSecret)
  TenantId: $(TenantId)

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

stages:
- stage: Create_Repo
  jobs:
  - job: Create_Repo
    displayName: 'Create Azure Repo'
    steps:
    - checkout: none
    - script: |
        echo "Logging in to Azure..."
        az login --service-principal -u $(ClientId) -p $(ClientSecret) --tenant $(TenantId)
      
        # Rest of your steps...
      displayName: 'Setup Azure Repo'
