trigger:
- master

name: Create Repo

parameters:
- name: RepoName
  displayName: Repo to be created

variables:
  azureServiceConnection: 'ash2'
  orgUrl: 'https://dev.azure.com/Dappverse'
  projectName: 'Alz'
  group: secrets

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

stages:
- stage: Create_Repo
  jobs:
  - job: Create_Repo
    displayName: 'Create Azure Repo'
    steps:
    - checkout: none
    - script: |
        echo "Logging in to Azure..."
        az login --service-principal -u ${{ secrets.clientId }} -p ${{ secrets.clientSecret }} --tenant ${{ secrets.tenantId }}

        echo "Configuring defaults..."
        az devops configure --defaults organization=$(orgUrl) project=$(projectName)
      
        echo "Creating a new Azure Repo named ${{ parameters.repoName }}..."
        az repos create --name ${{ parameters.repoName }}
      
        echo "Cloning the repository..."
        git clone $(repoUrl) ${{ parameters.repoName }}
        cd ${{ parameters.repoName }}
      
        echo "Creating folders in the repository..."
        mkdir Infra Docs Engg 
        git add .
        git commit -m "Create initial folders"
        git push origin master
      
        echo "Applying build policy to the repository..."
        az repos policy build create --blocking true --branch master --build-definition-id $(buildDefinitionId) --display-name "Build Policy" --enabled true --manual-queue-only false --queue-on-source-update-only true --repository-id $(repositoryId) --valid-duration 0
      displayName: 'Setup Azure Repo'
